### PR TITLE
Add function to generate openapi spec.

### PR DESCRIPTION
**Pull request by buildpeak**
This is a very simple version of OpenAPI spec just for internal use. At least the developer can use the Swagger page to do some RESTful tests.

### CODE REVIEW

**Comment by bauerji** [comment]
Hi,
Thank you for contribution. I am trying to access `/docs/` endpoint on both example applications. For `example_app.app` I am getting empty html response (20 status code). `example_app` gives me `404` for `/docs/`. Am I doing something wrong? I thought the example apps should run out of the box.
Jirka

**Comment by buildpeak** [comment]
Hi Jirka,

I just figured out the problem and fixed them.   Could you try again?

**Comment by bauerji** [comment]
It seems to work fine now. Except for path parameters. I could not find a way how to specify url path parameters while trying out the API through swagger UI. Would it be a simple fix or should we release it without it?

**Comment by buildpeak** [comment]
Hi,

Is this what you are looking for?

@app.route("/many/<int:count>",
***@***.***_docs(exceptions=[APIError(code=403,
msg="Access ***@***.***(response_many=True)def get_many(count:
int):
    """
    This route returns response containing many serialized objects.
    """
    return [
        ResponseModel(id=1, age=95, name="Geralt", nickname="White Wolf"),
        ResponseModel(id=2, age=45, name="Triss Merigold",
nickname="sorceress"),
        ResponseModel(id=3, age=42, name="Julian Alfred Pankratz",
nickname="Jaskier"),
        ResponseModel(id=4, age=101, name="Yennefer", nickname="Yenn"),
    ][:count]


Thanks

**Comment by bauerji** [comment]
Hey @buildpeak, I am sorry for such a late response. I've rebased your branch onto current master and I'm getting `ImportError: cannot import name 'parse_rule' from 'werkzeug.routing'` error. Apparently `werkzeug` marked the `parse_rule` method as internal in the latest release.

**Comment by The-Podsiadly** [comment]
@bauerji @buildpeak I found a workaround. Not the prettiest, but it works apparently according to `flask-restx` in this [PR #463](https://github.com/python-restx/flask-restx/pull/463).

```python
import re

RE_PARSE_RULE = re.compile(
    r"""
    (?P<static>[^<]*)                           # static rule data
    <
    (?:
        (?P<converter>[a-zA-Z_][a-zA-Z0-9_]*)   # converter name
        (?:\((?P<args>.*?)\))?                  # converter arguments
        \:                                      # variable delimiter
    )?
    (?P<variable>[a-zA-Z_][a-zA-Z0-9_]*)        # variable name
    >
    """,
    re.VERBOSE,
)

def parse_rule(rule):
    """
    Parse a rule and return it as generator. Each iteration yields tuples in the form
    ``(converter, arguments, variable)``. If the converter is `None` it's a static url part, otherwise it's a dynamic
    one.
    Note: This originally lived in werkzeug.routing.parse_rule until it was removed in werkzeug 2.2.0.
    """
    pos = 0
    end = len(rule)
    do_match = RE_PARSE_RULE.match
    used_names = set()
    while pos < end:
        m = do_match(rule, pos)
        if m is None:
            break
        data = m.groupdict()
        if data["static"]:
            yield None, None, data["static"]
        variable = data["variable"]
        converter = data["converter"] or "default"
        if variable in used_names:
            raise ValueError(f"variable name {variable!r} used twice.")
        used_names.add(variable)
        yield converter, data["args"] or None, variable
        pos = m.end()
    if pos < end:
        remaining = rule[pos:]
        if ">" in remaining or "<" in remaining:
            raise ValueError(f"malformed url rule: {rule!r}")
        yield None, None, remaining
```

**Pull request closed without merging**
