### PR TITLE
match flask pattern to return extra headers

### PR DESCRIPTION
**Pull request by cardoe**
Technically Flask allows you to return from a route with a tuple of 3
items with the last item being a dictionary of headers. The docs mention
it here: https://flask.palletsprojects.com/en/1.1.x/quickstart/#about-responses
This adjusts the behavior of the validate decorator to allow this as
well. Matches the behavior in: https://github.com/pallets/flask/blob/64213fc0214c1044fa2c9e60d0e2683e75d125c0/src/flask/app.py#L1644-L1646

### CODE REVIEW

**Comment by bauerji** [comment]
Hello @cardoe,

Thank you for contributing. Could please add tests to properly cover added functionality?

Jirka

**Comment by cardoe** [comment]
Sure. I didn't see where the existing behavior of returning the tuple was tested because that's where I wanted to add a test for this so I assumed it was untested in general. Can you point me to the right spot?

**Comment by bauerji** [comment]
Let's not test the point of returning the tuple. I was thinking about testing the overall functionality of modifying response header. I. e. create test route returning 3-tuple and check whether it really has an effect on response headers.

**Comment by cardoe** [comment]
I've implemented the test. Currently the testing fails on a test that's failing in master today.

**Comment by cardoe** [comment]
@bauerji let me know if this test solves the need or what other steps I need to do.

**Comment by bauerji** [comment]
Nice, thank you for contribution. I've made some adjustement in master branch, after rebasing all tests passed fine.

**Pull request merged**
